### ISSUE TITLE
Programmatically Determine if Secure Hub is Installed

### ISSUE THREAD

**Issue by roanutil** [citrix/citrix-mam-sdks#100]
For the iOS MAM SDK, what is the best way to determine at runtime if the 'Secure Hub' app is installed and logged in? I can see in the logs that the SDK is internally looking for it and may alert in the UI that it is not installed.

**Comment by makunterry** [comment]
The 'Secure Hub' URL is 'com.citrix.securehub' and you can use below method to determine it is installed or not:
https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl?language=objc
By doing this, you need to make sure your application Info.plist added 'com.citrix.securehub' correctly in the 'LSApplicationQueriesSchemes' field.

**Comment by roanutil** [comment]
@makunterry Thanks for your help.

I've added the `com.citrix.securehub` scheme to the `LSApplicationQueriesSchemes` array in my Info.plist. With the below code sample, it never returns `true`. Secure Hub is installed and entering the `com.citrix.securehub://` URL into Safari does open the app.

```swift
if await UIApplication.shared.canOpenURL(URL(string: "com.citrix.securehub://")!) {
    return
} else {
    fatalError()
}
```

**Comment by makunterry** [comment]
@roanutil 
thanks for your updating.
Please check carefully in your Info.plist and refer to the apple document:
https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl?language=objc

If the safari can open SecureHub by using 'om.citrix.securehub://' then the URL is correct.
