### ISSUE TITLE
Outdated CocoaPods

### ISSUE THREAD

**Issue by CaringDev** [citrix/citrix-mam-sdks#108]
On https://cocoapods.org/ the latest version is 22.8.0
Could you please publish the latest versions?

s.a. #69

**Comment by timliu55** [comment]
@CaringDev, the latest versions (23.11.0) were already on the cocoapods, but I don't know why the portal https://cocoapods.org/  still showed as 22.8.0
However, if you run `pod install` in your xcode project, it will definitely download latest 23.11.0

**Comment by CaringDev** [comment]
Thanks, and sorry for the noise. Indeed, the new versions are available.

**Comment by timliu55** [comment]
No worries, you are welcome
