### ISSUE TITLE
[iOS] CTXMAMCoreVersionString doesn't return framework version.

### ISSUE THREAD

**Issue by OgrePet** [citrix/citrix-mam-sdks#111]
Hello, I am trying to print Citrix SDK framework version to logs, but when printing CTXMAMCoreVersionString I receive this string "@(#)PROGRAM:CTXMAMCore  PROJECT:CTXMAMCore-1" instead of current framework version. And CTXMAMCoreVersionNumber returns 1.0 instead of version. Is it an issue or there is other way to get current version?

Thanks.

**Comment by dodododjk** [comment]
Hi,
The `CTXMAMCoreVersionString` variable is currently unavailable. Please use the NSBundle class to retrieve the version of the framework. An example is provided below:
```
// Get the system version of the framework using NSBundle
- (NSString *)getFrameworkVersion {
    NSBundle *bundle = [NSBundle bundleForClass:[CTXMAMCore class]];
    NSDictionary *infoDictionary = [bundle infoDictionary];
    NSString *version = [infoDictionary objectForKey:@"CFBundleShortVersionString"];
    return version;
}
```
Thanks.
