### ISSUE TITLE
iPadOS 17.4 crashes after app update

### ISSUE THREAD

**Issue by OgrePet** [citrix/citrix-mam-sdks#113]
On iPadOS 17.4 my application crashes when I install updated version with MAM SDK integrated. Here is a stack trace of this crash. 

<img width="634" alt="Screenshot 2024-03-11 at 18 11 24" src="https://github.com/citrix/citrix-mam-sdks/assets/758613/2d1db271-1b2a-4c53-843d-44c17260fecd">

Looks like  CTXMAMConfigManager calls UIKit code not from the main thread and this causes crash on iPad. Is there any way to workaround this while waiting for a fix?

Thanks.

**Comment by makunterry** [comment]
hi @OgrePet 
We are aware of this and is working on this fix, will release new MAMSDK soon.
Before the offical release, if you are looking for a workaround, you can remove the app and re-install the app.

**Comment by shafersystems** [comment]
@makunterry do you have a planned release date?   This is currently blocking the release of our application.

**Comment by makunterry** [comment]
@OgrePet, @shafersystems 
Sure, you can expecting the new release within 24 hours.

**Comment by makunterry** [comment]
@OgrePet and @shafersystems 
The new MAM SDK is released, and also update on Cocoapods.
