### ISSUE TITLE
iOS 15 -  ERROR:  Unknown loader command found  in the application binary image

### ISSUE THREAD

**Issue by raphaelguye** [citrix/citrix-mam-sdks#51]
## Description

There is an error at build time for iOS App with the iOS Deployment Target is set to 15.0.
![project-config-ios15](https://user-images.githubusercontent.com/1267845/138068498-a4d2918e-0d09-4be9-a3b0-b69d7e2c3806.png)

## Expected behaviour

Build is working with same output we have for iOS 14:
![ios14-success](https://user-images.githubusercontent.com/1267845/138068300-d1b7e03d-403f-453e-bc8b-322e9c72c7f2.png)

## Actual behaviour

```
2021-10-20 11:35:36.787 CGAppCLPrepTool[2926:78706] [ToolkitLib] ERROR:  Unknown loader command found  in the application binary image.
ERROR:  Unknown loader command found  in the application binary image.
------------------------------
2021-10-20 11:35:36.790 CGAppCLPrepTool[2926:78706] [CommandLine] ERROR:  Unknown loader command found  in the application binary image.
------------------------------

```
<img width="1236" alt="ios15-error" src="https://user-images.githubusercontent.com/1267845/138068311-e652519a-0a8d-4a20-8a2f-ad0184706c07.png">

## Step to reproduce

1. Download the sample project from https://github.com/raphaelguye/DemoCitrixMam
2. Open the project DemoCitrixMam.xcodeproj
3. Fix the Code signing if necessary
4. Build with 'Any iOS Device' (not with the simulator)

_NB: You can come back on commit c077785bed04715c81d4a3db06ddc11122568599 to have a success build on iOS 14 (check the [history](https://github.com/raphaelguye/DemoCitrixMam/commits/main))_

**Comment by jaspreet1** [comment]
Thank you @raphaelguye and @GeroHerkenrath for your inputs! 

We are aware of this duplicate argument issue and is expected to be fixed in our future releases. (CXM-101281)

You were right, I was using a simulator build. I see the _Unknown loader command found_ issue now. We'll start looking at this error asap.
In the mean time, .mdx file generated with the simulator device should be good to use. Let me know if you face any issues with that.

**Comment by raphaelguye** [comment]
When have you planned to release officially the fixed version of CGPrepTool ?

**Comment by raphaelguye** [comment]
The same issue happens with the CGPrepTool of the **MDX Toolkit** app. 

It happens with the `Wrap` option (instead of `SdkPrep`) when we try to resign and create the MDX for an existing IPA without the MAM sdk.

There is a failure in the Rebuilding app step:
```
$ /Applications/Citrix/MDXToolkit/CGAppCLPrepTool Wrap -Cert "My certificate" -Profile my_enterprise_profile.mobileprovision -in my_app_ios15.ipa -out ./my_app_ios15_enterprise.mdx -appDesc "My App 1.0" -appName "MyApp" -bundleID "com.my.mbundle" -minPlatform "15.0"

#
# ...
#

Validating dylib......
------------------------------


Rebuilding app......
------------------------------
 final  ldCmdOrdOfCtxDylib 18 
addCitrixDylib: check dylib failed: /var/folders/p9/pkr6s90s4_15p4ds0b3q3k9c0000gn/T/com.citrix.mdx/E242C890-E0AC-42D6-9CEA-171984B42BF1-11013-00000C67505251EA/Payload/MyApp.app/MyApp 1115


ERROR:  Unknown loader command found  in the application binary image.
------------------------------
2022-01-27 16:18:15.633 CGAppCLPrepTool[11013:189646] [CommandLine] ERROR:  Unknown loader command found  in the application binary image.
```

I get this error when I try to wrap an app build with the sdk 15.0 of iOS.
With the sdk 12.0, the same command works.

**Comment by raphaelguye** [comment]
Hello @jaspreet1 , yes thank you ! The issue is solved now with the MAM sdk.

I have now the same request for the [MDX Toolkit](https://docs.citrix.com/en-us/mdx-toolkit/overview.html).
I know it not the ideal place to ask this question, but I don't have another entry point.

Can you please forward this issue to one of your colleague in charge?

In fact, the same issue is happening with the current stable version of the MDX Toolkit and applications target iOS 15.

**Comment by raphaelguye** [comment]
yes @jaspreet1. Swift app target iOS 15+. Wrapped with the MDX toolkit.

**Comment by jaspreet1** [comment]
Hi @raphaelguye, MDX Toolkit has end-of-life from July 2022. Anyway, Citrix doesn't officially support wrapping Swift apps using MDX Toolkit. Our recommendation is to integrate Citrix MAMSDK with the Swift apps.

**Comment by jaspreet1** [comment]
Hi @raphaelguye, I believe you might have gotten some help for MDX Toolkit issue as well. Can we close this GitHub issue now?

**Comment by raphaelguye** [comment]
Yes thank you, we can close the issue.
We will use only the MAM sdk in the future for iOS 15+ apps.
