### ISSUE TITLE
MAM SDK (iOS) - how to get username

### ISSUE THREAD

**Issue by mylvs** [citrix/citrix-mam-sdks#58]
We are in the process of migrating MDM to MAM SDK.  My devs are struggling to get the username out of MAM.  The username shown in the apps provides certainty that the one using the app is the one who was logged in.  We can't find anything in the net that can help us solve this problem.
Our apps need this information in the first instance when opening the app.  If we don't have this info our apps won't work and it is difficult to retrieve this from our end.  I would really appreciate the help that we can get as the EOL timeline is due in few months time.

**Comment by jaspreet1** [comment]
Hi @mylvs, This week we have published a new public MAMSDK release 22.1.0. This new SDK exposes a new public class  <CTXMAMAppCore/CTXMAMUserAttributes.h> to get username. 

Download page: https://www.citrix.com/downloads/citrix-endpoint-management/product-software/mdx-toolkit.html
Documentation: https://developer.cloud.com/citrixworkspace/mobile-application-integration/mam-sdk-for-ios-and-ipados/docs/ctxmamuserattributes.h

But this requires adding SEND_LDAP_ATTRIBUTES client property to the configured CEM server. Check either of the following documents for more information on adding this:
1. https://docs.citrix.com/en-us/xenmobile/server/provision-devices/client-properties.html#client-property-reference (search for or scroll to SEND_LDAP_ATTRIBUTES item)
2. https://docs.citrix.com/en-us/citrix-endpoint-management/citrix-endpoint-management.pdf (search for SEND_LDAP_ATTRIBUTES  item under the "Client property reference" section)

Hope this helps.

**Comment by PedroCitrix** [comment]
@mylvs, @jaspreet1 - Apologies, this new API was intended to be released on version 22.1.0, but it has been delayed until the next release which is expected to be released early in March.

**Comment by mylvs** [comment]
Hi Pedro,

Thanks for the information.
Does it mean we cannot use the new API soon?
I'm just wondering about the timing of this.  We have 4 apps that we are working on right now with major projects are starting to kick-in.
This changes needs to go to our proper SDLC process.
The timeline we are having are a bit tight knowing that everything needs to be in place before July 2022.  It is just basically giving us 3 months to deal with it.

Just letting you know the challenges we are facing as of now.

Thanks,
Myla

**Comment by jaspreet1** [comment]
Hi @mylvs , The new SDK release 22.4.0 has the required APIs mentioned earlier. Refer to <CTXMAMAppCore/CTXMAMUserAttributes.h>

**Comment by mylvs** [comment]
Thanks @jaspreet1 for always keeping me updated.
