### ISSUE TITLE
Get app policies configured on XenMobile server from CTXMAMConfigManager on iOS

### ISSUE THREAD

**Issue by hendrik-dev** [citrix/citrix-mam-sdks#62]
We have configured several custom app policies which we have defined in policy_metadata and included in our MDX file.
 
After migrating to the MAM SDK for iOS we are no longer able to read the values that the admin has configured for the app policies on the XenMobile server.
 
CTXMAMConfigManager provides multiple methods to retrieve configuration values like getConfigurationAsStringForKey. However each of those methods simply returns nil.
During debugging we can see that CTXMAMConfigManager has received all of the app policies and the corresponding values. They can be seen in an internal NSDictionary object. This object is a private property though and there is no method to access these values.
 
How can the app policies and and their values be retrieved using the MAM SDK for iOS?

**Comment by jaspreet1** [comment]
Hi @hendrik-dev, In 22.3.0 MAM SDK release, we have published the following new CTXMAMConfigManager API to get the policy values.  Hope this helps.
```
/*!
 @brief getPolicyValueForKey function will retrieve the custom policy value or client property for the specified key.
 @param key A string that represents the key for the policy of the value which is to be retrieved.
 @param error An out parameter where an error will be saved in case one occurs.
 @returns The id of the value for the policy which was retrieved. This value has to be cast to the type of the value for the specified policy.
 @discussion For boolean, int, float, and similar values, use NSNumber for casting the value.
 */
-(id)             getPolicyValueForKey:                     (NSString *) key    outError:     (NSError **)     error;
```

**Comment by hendrik-dev** [comment]
Thank you, the new API in the updated SDK solves this problem.
