### ISSUE TITLE
Package manger versions

### ISSUE THREAD

**Issue by CaringDev** [citrix/citrix-mam-sdks#69]
E.g. here https://github.com/citrix/citrix-mam-sdks/commit/54c7b01ee1ffb7e928b7e672ff3f93fe67153b64 there seem to be new versions. However, they do not end up on [Cocoapods.org](https://github.com/CocoaPods/Specs/tree/master/Specs/7/3/4/CTXMAMCore) where the latest version is 21.9

The same seems to be true for NuGet, where the [latest versions](https://www.nuget.org/packages?q=citrix.mam) currently are 21.6.x

Is this a glitch in a publish pipeline or should we really copy the assets manually? I'd rather follow the guideline in https://github.com/citrix/citrix-mam-sdks#ios to use a package manager.

**Comment by makunterry** [comment]
@CaringDev 
Thanks for your information, we will check this issue and will fix the version if there is any mismatch.

**Comment by Annie-XIE** [comment]
@CaringDev 
As for nuget, yes, the current version is old (21.6.x). We have planned to release to nuget with the latest version. The date to release it isn't finalized. Will let you know as soon as we get it released. Thanks!

**Comment by xingliangt** [comment]
mamsdk 22.9.0 is released in github maven,you can consume on your gradle dependency
thank you

**Comment by CaringDev** [comment]
Thanks, however I'm using CocoaPods, not gradle nor NuGet, i.e. (for me) this is not really helpful.
